// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package schema

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// NewPet defines model for NewPet.
type NewPet struct {
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	DateOfBirth *openapi_types.Date `json:"dateOfBirth,omitempty"`
	Email       openapi_types.Email `json:"email"`
	FirstName   string              `json:"firstName"`
	LastName    string              `json:"lastName"`
}

// Pet defines model for Pet.
type Pet struct {
	// Id ペットのユニークID
	Id   int     `json:"id"`
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
}

// User defines model for User.
type User struct {
	// CreateDate ユーザー情報の作成日時
	CreateDate  *openapi_types.Date `json:"createDate,omitempty"`
	DateOfBirth *openapi_types.Date `json:"dateOfBirth,omitempty"`
	Email       openapi_types.Email `json:"email"`

	// EmailVerified ユーザーがメール認証を完了しているかどうか。
	// 完了していればtrue。
	EmailVerified bool   `json:"emailVerified"`
	FirstName     string `json:"firstName"`

	// Id ユーザーのユニークID.
	Id       int    `json:"id"`
	LastName string `json:"lastName"`
}

// FindPetsParams defines parameters for FindPets.
type FindPetsParams struct {
	// Tags 検索したいペットのタグ情報
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// Limit 検索件数の上限
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = NewUser

// UpdateUserByIDJSONRequestBody defines body for UpdateUserByID for application/json ContentType.
type UpdateUserByIDJSONRequestBody = NewUser
