root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api -v ./app/src/cmd/api"
bin = "tmp/api"
full_bin = "./tmp/api"
include_ext = ["go"]
exclude_dir = ["tmp"]
include_dir = ["app"]
exclude_file = []
exclude_unchanged = true
log = "api.air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[misc]
clean_on_exit = true
